config/routes.rb
Rails.application.routes.draw do

  get 'rys_management/:rys_id/edit', to: 'rys_management#edit', as: 'rys_management_edit', rys_id: /[^\/]+/
  put 'rys_management/:rys_id/update', to: 'rys_management#update', as: 'rys_management_update', rys_id: /[^\/]+/
  post 'rys_management/toggle_feature(/:id)', to: 'rys_management#toggle_feature', as: 'rys_management_toggle_feature'

end

app/controllers/rys_management_controller.rb
class RysManagementController < ApplicationController

  before_action :require_admin
  before_action :find_plugin, only: [:edit, :update]
  before_action :find_feature_record, only: [:toggle_feature]

  accept_api_auth :toggle_feature

  def edit
    @easy_settings = EasySettings::FormModel.new(prefix: @rys_plugin.rys_id)
  end

  def update
    if params[:easy_setting]
      @easy_settings = EasySettings::ParamsWrapper.from_params(params[:easy_setting].permit!, prefix: @rys_plugin.rys_id)

      if @easy_settings.save
        # All good
      else
        render :edit
        return
      end
    end

    flash[:notice] = l(:notice_successful_update)
    redirect_back_or_default rys_management_edit_path(@rys_plugin.rys_id)
  end

  def toggle_feature
    @feature_record.active = params[:active].to_s.to_boolean
    @feature_record.save

    respond_to do |format|
      format.api { render_api_ok }
      format.html { redirect_back_or_default admin_plugins_path }
    end
  end

  private

    def find_plugin
      @rys_plugin = RysManagement.find(params[:rys_id])
      render_404 if @rys_plugin.nil?
    end

    def find_feature_record
      @feature_record = RysFeatureRecord.mutli_find(params[:id])
      render_404 if !@feature_record.is_a?(RysFeatureRecord)
    end

end

app/views/admin/rys_management/_view_admin_plugins_bottom.html.erb
<h2><%= l('rys.rys_plugins') %></h2>

<div class="autoscroll">
<table class="list">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% RysManagement.all do |plugin| %>
      <tr>
        <td><%= plugin.name %></td>
        <td><%= plugin.description %></td>
        <td><%= plugin.feature_records_count %></td>

        <td class="buttons text-right">
          <% if plugin.plugin_active? %>
            <%= link_to l(:button_edit), rys_management_edit_path(plugin.rys_id), class: 'icon icon-edit' %>
          <% else %>
            <%= plugin.deactivated_plugin_html(self) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<h3><%= l('rys_management.other_features') %></h3>

<%= render 'rys_management/features_table', features: RysFeatureRecord.registered_for(nil) %>

app/views/rys_management/_features_table.html.erb
<div class="autoscroll">
<table class="list">
  <thead>
    <tr>
      <th><%= l(:field_name) %></th>
      <th><%= l(:field_description) %></th>
      <th><%= l(:field_active) %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% features.sort_by{|r| r.name.split('.') }.each do |feature| %>
      <tr>
        <td class="subject" style="color: <%= feature.active? ? 'green' : 'red' %>"><%= feature.feature.title %></td>
        <td><%= feature.feature.description %></td>
        <td><%= checked_image(feature.active) %></td>
        <td class="buttons text-right">
          <% if feature.active? %>
            <%= link_to l('rys_management.deactivate'), rys_management_toggle_feature_path(feature, active: '0', back_url: request.fullpath), method: 'POST' %>
          <% else %>
            <%= link_to l('rys_management.activate'), rys_management_toggle_feature_path(feature, active: '1', back_url: request.fullpath), method: 'POST' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/rys_management/edit.html.erb
<% html_title @rys_plugin.name %>

<h2>
  <%= @rys_plugin.name %>

  <% if @rys_plugin.prerelease? %>
    <span class="rys_management_indicator-beta">Beta</span>
  <% end %>
</h2>

<h4 class="u-text--bold"><%= l('rys.features') %></h4>

<%= render 'rys_management/features_table', features: @rys_plugin.feature_records %>

<% if lookup_context.template_exists?(@rys_plugin.edit_partial_path, nil, :partial) %>
  <h4 class="u-text--bold"><%= l('label_settings') %></h4>

  <%= form_for(@easy_settings, url: rys_management_update_path(@rys_plugin.rys_id), method: 'PUT', html: { class: 'form-box easy-setting-plugin-form tabular' }) do |form| %>
    <%= hidden_field_tag :back_url, request.fullpath %>

    <%= render @rys_plugin.edit_partial_path, rys_plugin: @rys_plugin, form: form %>

    <div class="form-actions">
      <%= form.submit l(:button_update), class: 'buttom button-positive' %>

      <% if params[:back_url].present? %>
        <%= link_to l(:button_back), params[:back_url], class: 'button' %>
      <% end %>
    </div>
  <% end %>
<% end %>